package br.com.persist.plugins.objeto;

public class ObjetoConstantes {
	public static final String ALTURMA_MINIMA_FORMULARIO_DADOS_TOOLBAR_TABLEHEADER = "ALTURMA_MINIMA_FORMULARIO_DADOS_TOOLBAR_TABLEHEADER";
	public static final String ALTURMA_MINIMA_FORMULARIO_MAXIMO_DE_REGISTROS = "ALTURMA_MINIMA_FORMULARIO_MAXIMO_DE_REGISTROS";
	public static final String ALTURMA_MINIMA_FORMULARIO_SEM_REGISTROS = "ALTURMA_MINIMA_FORMULARIO_SEM_REGISTROS";
	public static final String DELTA_AJUSTE_FORM_DISTANCIA_VERTICAL = "DELTA_AJUSTE_FORM_DISTANCIA_VERTICAL";
	public static final String DESTACAR_PROPRIO_LARGURA_INTERNAL = "DESTACAR_PROPRIO_LARGURA_INTERNAL";
	public static final String DESTACAR_PROPRIO_ALTURA_INTERNAL = "DESTACAR_PROPRIO_ALTURA_INTERNAL";
	public static final String DELTA_X_AJUSTE_FORM_OBJETO = "DELTA_X_AJUSTE_FORM_OBJETO";
	public static final String DELTA_Y_AJUSTE_FORM_OBJETO = "DELTA_Y_AJUSTE_FORM_OBJETO";

	private ObjetoConstantes() {
	}
}