package br.com.persist.assistencia;

import java.awt.BasicStroke;
import java.awt.Dimension;
import java.awt.Stroke;
import java.io.File;

public class Constantes {
	public static final String LABEL_CONFIGURACOES_MIN = "label.configuracoes_min";
	public static final Dimension DIMENSION_FILE_CHOOSER = new Dimension(600, 600);
	public static final String LABEL_INSERT_CMP_OBRIG = "label.insert_cmp_obrig";
	public static final String LABEL_CONFIRMA_SALVAR = "label.confirma_salvar";
	public static final String LABEL_CONFIGURACOES = "label.configuracoes";
	public static final String IMAGEM_TRAY_ICON = "/resources/create.png";
	public static final String LABEL_UTILITARIOS = "label.utilitarios";
	public static final String LABEL_MAPEAMENTOS = "label.mapeamentos";
	public static final String LABEL_SINCRONIZAR = "label.sincronizar";
	public static final String LABEL_ALTERNATIVO = "label.alternativo";
	public static final String LABEL_FORMULARIO = "label.formulario";
	public static final String PERSISTENCIA_FVF = "persistencia.fvf";
	public static final String LABEL_METADADOS = "label.meta_dados";
	public static final String LABEL_AMBIENTES = "label.ambientes";
	public static final String LABEL_VARIAVEIS = "label.variaveis";
	public static final String[] ARRAY_LENGTH_ZERO = new String[0];
	public static final String LABEL_ATUALIZAR = "label.atualizar";
	public static final String LABEL_FRAGMENTO = "label.fragmento";
	public static final String LABEL_COM_ASPAS = "label.com_aspas";
	public static final String LABEL_SEM_ASPAS = "label.sem_aspas";
	public static final String LABEL_APARENCIA = "label.aparencia";
	public static final String GC_PREFERENCIAL = "GC_PREFERENCIAL";
	public static final String GC_O_FORMULARIO = "GC_O_FORMULARIO";
	public static final Dimension SIZE2 = new Dimension(900, 700);
	public static final Dimension SIZE3 = new Dimension(400, 400);
	public static final Dimension SIZE = new Dimension(1000, 700);
	public static final Stroke STROKE_PADRAO = new BasicStroke(2);
	public static final String LABEL_EXECUTAR = "label.executar";
	public static final String LABEL_DESTACAR = "label.destacar";
	public static final String LABEL_ARRASTAR = "label.arrastar";
	public static final String LABEL_CONSULTA = "label.consulta";
	public static final String LABEL_FICHARIO = "label.fichario";
	public static final String LABEL_ARQUIVOS = "label.arquivos";
	public static final String LABEL_CIRCULAR = "label.circular";
	public static final String LABEL_CONEXAO2 = "label.conexao2";
	public static final String LABEL_ENTIDADE = "label.entidade";
	public static final String LABEL_IGNORAR = "label.ignorar";
	public static final String LABEL_TABELAS = "label.tabelas";
	public static final String LABEL_ARQUIVO = "label.arquivo";
	public static final String LABEL_ATENCAO = "label.atencao";
	public static final String LABEL_CONEXAO = "label.conexao";
	public static final String LABEL_DIALOGO = "label.dialogo";
	public static final String LABEL_DESKTOP = "label.desktop";
	public static final String LABEL_LIMPAR2 = "label.limpar2";
	public static final String LABEL_APLICAR = "label.aplicar";
	public static final String LABEL_OBJETO = "label.objeto";
	public static final String LABEL_UPDATE = "label.update";
	public static final String LABEL_DELETE = "label.delete";
	public static final String LABEL_INSERT = "label.insert";
	public static final String LABEL_LIMPAR = "label.limpar";
	public static final String LABEL_ANEXOS = "label.anexos";
	public static final String LABEL_FECHAR = "label.fechar";
	public static final String DESCONECTADO = "DESCONECTADO";
	public static final String CONEXAO_NULA = "CONEXAO_NULA";
	public static final String LABEL_BANCO = "label.banco";
	public static final String LABEL_VAZIO = "label.vazio";
	public static final String CHAVE_VALOR = "chave_valor";
	public static final String SEPARADOR = File.separator;
	public static final String LABEL_NOVO = "label.novo";
	public static final String COR_FONTE = "COR_FONTE:";
	public static final int TREZENTOS_QUARENTA_UM = 341;
	public static final String CONECTADO = "CONECTADO";
	public static final String IGNORADOS = "ignorados";
	public static final String SERVICE = "Service";
	public static final String IMAGENS = "imagens";
	public static final String SELECT = "SELECT ";
	public static final String DIALOG = "DIALOG";
	public static final String CAMPOS = "CAMPOS";
	public static final String ICONE = "ICONE:";
	public static final String CAMPO = "CAMPO";
	public static final String FICHA = "FICHA";
	public static final String VALOR = "valor";
	public static final int QUATROCENTOS = 400;
	public static final String SEP2 = "_$$$_";
	public static final String ERRO = "ERRO";
	public static final String INFO = "INFO";
	public static final String FORM = "FORM";
	public static final String NOVO = "novo";
	public static final String EXEC = "exec";
	public static final int QUARENTA_UM = 41;
	public static final int VINTE_CINCO = 25;
	public static final String TAB2 = "\t\t";
	public static final String QL2 = "\n\n";
	public static final int DUZENTOS = 200;
	public static final String III = "???";
	public static final String ESC = "esc";
	public static final String SEP = "###";
	public static final int QUARENTA = 40;
	public static final String TAB = "\t";
	public static final String VAZIO = "";
	public static final String QL = "\n";
	public static final int SETENTA = 70;
	public static final int TRINTA = 30;
	public static final int GRADE = 16;
	public static final int VINTE = 20;
	public static final String U = "_";
	public static final int QUATRO = 4;
	public static final int CINCO = 5;
	public static final int CEM = 100;
	public static final int ZERO = 0;
	public static final int TRES = 3;
	public static final int DOIS = 2;
	public static final int DEZ = 10;
	public static final int UM = 1;

	private Constantes() {
	}
}