package br.com.persist.componente;

public enum BarraButtonEnum {
	NOVO, BAIXAR, BAIXAR2, LIMPAR, LIMPAR2, SALVAR, COPIAR, COPIAR2, COLAR, COLAR2, DESTAC_EM_FORM, RETORNAR_AO_FICHARIO, ABRIR_EM_F0RM, CLONAR_EM_FORM,
}