package br.com.persist.componente;

public enum BarraButtonEnum {
	DESTACAR_EM_FORMULARIO, RETORNAR_AO_FICHARIO, CLONAR_EM_FORMULARIO, ABRIR_EM_FORMULARO, NOVO, SALVAR, SALVAR_COMO, ATUALIZAR, EXCLUIR, LIMPAR, LIMPAR2, BAIXAR, BAIXAR2, COPIAR, COPIAR2, COLAR, COLAR2, APLICAR
}